//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Optimate {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class OptiMateProtocol : ObservableObject, System.ComponentModel.INotifyPropertyChanged {
        
        private byte versionField;
        
        private OptiMateProtocolOptiStructure[] optiStructuresField;
        
        private string protocolDisplayNameField;
        
        /// <remarks/>
        public byte version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OptiStructure", IsNullable=false)]
        public OptiMateProtocolOptiStructure[] OptiStructures {
            get {
                return this.optiStructuresField;
            }
            set {
                this.optiStructuresField = value;
                this.RaisePropertyChanged("OptiStructures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolDisplayName {
            get {
                return this.protocolDisplayNameField;
            }
            set {
                this.protocolDisplayNameField = value;
                this.RaisePropertyChanged("ProtocolDisplayName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OptiMateProtocolOptiStructure : ObservableObject, System.ComponentModel.INotifyPropertyChanged {
        
        private OptiMateProtocolOptiStructureInstruction[] instructionField;
        
        private string structureIdField;
        
        private bool isHighResolutionField;
        
        private bool isNewField;
        
        private bool isNewFieldSpecified;
        
        private string typeField;
        
        private string baseStructureField;
        
        public OptiMateProtocolOptiStructure() {
            this.isHighResolutionField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Instruction")]
        public OptiMateProtocolOptiStructureInstruction[] Instruction {
            get {
                return this.instructionField;
            }
            set {
                this.instructionField = value;
                this.RaisePropertyChanged("Instruction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructureId {
            get {
                return this.structureIdField;
            }
            set {
                this.structureIdField = value;
                this.RaisePropertyChanged("StructureId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isHighResolution {
            get {
                return this.isHighResolutionField;
            }
            set {
                this.isHighResolutionField = value;
                this.RaisePropertyChanged("isHighResolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
                this.RaisePropertyChanged("isNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isNewSpecified {
            get {
                return this.isNewFieldSpecified;
            }
            set {
                this.isNewFieldSpecified = value;
                this.RaisePropertyChanged("isNewSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseStructure {
            get {
                return this.baseStructureField;
            }
            set {
                this.baseStructureField = value;
                this.RaisePropertyChanged("BaseStructure");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class OptiMateProtocolOptiStructureInstruction : ObservableObject, System.ComponentModel.INotifyPropertyChanged {
        
        private OperatorType operatorField;
        
        private bool operatorFieldSpecified;
        
        private string defaultTargetField;
        
        private string targetField;
        
        private string operatorParameterField;
        
        private string operatorParameter2Field;
        
        private string operatorParameter3Field;
        
        private string operatorParameter4Field;
        
        private string operatorParameter5Field;
        
        private string operatorParameter6Field;
        
        private string operatorParameter7Field;
        
        private bool isNewField;
        
        private bool isNewFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OperatorType Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
                this.RaisePropertyChanged("OperatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultTarget {
            get {
                return this.defaultTargetField;
            }
            set {
                this.defaultTargetField = value;
                this.RaisePropertyChanged("DefaultTarget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("Target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorParameter {
            get {
                return this.operatorParameterField;
            }
            set {
                this.operatorParameterField = value;
                this.RaisePropertyChanged("OperatorParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorParameter2 {
            get {
                return this.operatorParameter2Field;
            }
            set {
                this.operatorParameter2Field = value;
                this.RaisePropertyChanged("OperatorParameter2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorParameter3 {
            get {
                return this.operatorParameter3Field;
            }
            set {
                this.operatorParameter3Field = value;
                this.RaisePropertyChanged("OperatorParameter3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorParameter4 {
            get {
                return this.operatorParameter4Field;
            }
            set {
                this.operatorParameter4Field = value;
                this.RaisePropertyChanged("OperatorParameter4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorParameter5 {
            get {
                return this.operatorParameter5Field;
            }
            set {
                this.operatorParameter5Field = value;
                this.RaisePropertyChanged("OperatorParameter5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorParameter6 {
            get {
                return this.operatorParameter6Field;
            }
            set {
                this.operatorParameter6Field = value;
                this.RaisePropertyChanged("OperatorParameter6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorParameter7 {
            get {
                return this.operatorParameter7Field;
            }
            set {
                this.operatorParameter7Field = value;
                this.RaisePropertyChanged("OperatorParameter7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
                this.RaisePropertyChanged("isNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isNewSpecified {
            get {
                return this.isNewFieldSpecified;
            }
            set {
                this.isNewFieldSpecified = value;
                this.RaisePropertyChanged("isNewSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum OperatorType {
        
        /// <remarks/>
        UNDEFINED,
        
        /// <remarks/>
        copy,
        
        /// <remarks/>
        margin,
        
        /// <remarks/>
        or,
        
        /// <remarks/>
        and,
        
        /// <remarks/>
        crop,
        
        /// <remarks/>
        sub,
        
        /// <remarks/>
        subfrom,
    }
}
